ldproxy/ldproxy

ogcapi-draft/ogcapi-html/src/main/java/de/ii/ldproxy/target/html/FeatureTransformerHtml.java
ogcapi-draft/ogcapi-html/src/main/java/de/ii/ldproxy/target/html/FeatureTransformerHtmlComplexObjects.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ldproxy/target/geojson/FeatureTransformerGeoJson.java
xtraplatform.gradle

This allows to combine two columns from the same table. To enable it, in the property path in the provider configuration, define two columns separated by `:`, e.g.:
```
process:
path: /observation/[process_fk=id]process/category_fk:id
type: STRING
```
The value for `process` will then be the values of the two columns separated by `|||`.
In the service configuration, `stringFormat` can be then be used like this:
```
process:
stringFormat: "{{serviceUrl}}/collections/process/{{value | replace:'\\|\\|\\|':'/items/'}}"
```
A cleaner solution that removes the `|||` seperator should be considered in the context of #162. It would require to implement transformers in the provider. The above example would then require two `stringFormat`, one in the provider and one in the service:
``` …
```

combine two properties

---

xtraplatform.gradle

Fixes #192. 
Every table with mapped columns needs a sort key. Until now it was expected that every table has a numeric column with the same name that is used as sort key. The default sort key column name was already configurable:
```yml
connectionInfo:
pathSyntax:
defaultSortKey: id
```
This PR introduces support for string columns as sort key. Additionally it allows to set a different sort key per table:
```yml
managementrestrictionorregulationzone:
sourcePath: /am_managementrestrictionorregulationzone{sortKey=inspireid}
type: OBJECT
properties:
legislationCitation:
sourcePath: '[id=id_managementrestrictionorregulationzone]am_manrestreg_legcit/[id_legislationcitation=id]am_legislationcitation{sortKey=identificationnumber}'
type: OBJECT_ARRAY
```
Only the table at the end of the path …

sort keys and constants

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/infra/rest/ExceptionMapper.java

... since we do not have access to the external URL when the response is created. However, log the relative path.
closes #243

remove instance from exception responses

---

ogcapi-draft/ogcapi-collections-queryables/src/main/java/de/ii/ldproxy/ogcapi/collections/queryables/app/EndpointQueryables.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ldproxy/ogcapi/collections/schema/EndpointSchema.java
ogcapi-draft/ogcapi-collections-style-info/src/main/java/de/ii/ldproxy/ogcapi/collections/styleinfo/EndpointManageStyleInfo.java
ogcapi-draft/ogcapi-features-geojson-ld/src/main/java/de/ii/ldproxy/ogcapi/features/geojsonld/app/EndpointJsonLdContext.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/EndpointDapa.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/EndpointObservationProcessing.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/EndpointVariables.java
ogcapi-draft/ogcapi-resources-manager/src/main/java/ii/de/ldproxy/resources/manager/EndpointResourcesManager.java
ogcapi-draft/ogcapi-resources/src/main/java/de/ii/ldproxy/resources/app/EndpointResource.java
ogcapi-draft/ogcapi-resources/src/main/java/de/ii/ldproxy/resources/app/EndpointResources.java
ogcapi-draft/ogcapi-styles-manager/src/main/java/de/ii/ldproxy/ogcapi/styles/app/manager/EndpointStyleMetadataManager.java
ogcapi-draft/ogcapi-styles-manager/src/main/java/de/ii/ldproxy/ogcapi/styles/app/manager/EndpointStylesManager.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ldproxy/ogcapi/styles/app/EndpointStyle.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ldproxy/ogcapi/styles/app/EndpointStyleMetadata.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ldproxy/ogcapi/styles/app/EndpointStyles.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetSingleCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetsMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetsSingleCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSingleCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/EndpointTileMatrixSets.java
ogcapi-draft/ogcapi-transactional/src/main/java/de/ii/ldproxy/ogcapi/features/transactional/EndpointTransactional.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ldproxy/ogcapi/collections/infra/EndpointCollection.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ldproxy/ogcapi/collections/infra/EndpointCollections.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/common/infra/EndpointConformance.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/common/infra/EndpointDefinition.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/common/infra/EndpointLandingPage.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/EndpointFeatures.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/Endpoint.java

The api definition caching did not take into account that configurations may change at runtime. I changed the cache key from the id to a hashsum to address this.

fix api definition caching

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/PathParameterFeatureIdFeatures.java

Feature ID URI pattern now allows a dot symbol to avoid 404 errors for features with a dot symbol

Fix error 404 for features with a dot symbol in the ID

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/OgcApiDataV2.java

The previous fix for merging extents did not cover all cases. This could lead to infinite recursion.

extent merging still not correct

---

ogcapi-draft/ogcapi-features-geojson-ld/src/main/java/de/ii/ldproxy/ogcapi/features/geojsonld/app/ContextFormatExtension.java
ogcapi-draft/ogcapi-features-geojson-ld/src/main/java/de/ii/ldproxy/ogcapi/features/geojsonld/app/ContextFormatJsonLd.java
ogcapi-draft/ogcapi-features-geojson-ld/src/main/java/de/ii/ldproxy/ogcapi/features/geojsonld/app/EndpointJsonLdContext.java

The new onStartup() checks always failed for the GEO_JSON_LD module, because no FormatExtension was used for the context. The module has been updated to properly define and use a format extension.

GeoJSON-LD startup fix

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesQueryImpl.java

In these cases OR fails, because we have only a single operand

bugfix: handle cases with one q value and a single q queryable

---

docs/de/configuration/services/building-blocks/features-core.md
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesQueryImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/domain/FeaturesCoreConfiguration.java

This PR starts to address #399. It adds the capability to specify the number of maximum number decimal digits in coordinates depending on the unit of the number. The default is still that no digits are cut. 
Example: 
```yaml
- buildingBlock: FEATURES_CORE
coordinatePrecision:
metre: 2
degree: 7
``` 
Open issues:
- There can be different units in a CRS (in particular - horizontal is degrees, vertical is meters). Currently there is only one precision value for all axes.
- The HTML Filter editor also creates coordinates for the `bbox` parameter that have some 15 decimal places or so. Since this one is always in degrees and just a rough filter, maybe always restrict this to 4 decimal places (approx 11 meters) or so?
- Currently only meter and degree are supported as units. For the typical …

add coordinatePrecision option

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/OgcApiDataV2.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/infra/rest/RequestContextBinder.java
ogcapi-stable/ogcapi-foundation/src/test/groovy/de/ii/ldproxy/ogcapi/infra/json/SchemaValidatorSpec.groovy
xtraplatform.gradle

Closes #427.
I migrated the recommended patterns, fixed all compile and runtime errors and tested some APIs. There don't seem to be any obvious issues.
I had to disable some tests in `SchemaValidatorSpec` which are no longer throwing NPEs. I would suspect that the default behaviour when parsing empty strings changed for `ObjectMapper`. Not sure how useful these tests were in the first place.

Dropwizard 2.0

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesQueryImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/domain/AbstractQueryParameterDatetime.java

closes #481
See also https://github.com/interactive-instruments/xtraplatform-spatial/pull/83 for the changes in xtraplatform-spatial. The main changes are in that PR to extend the CQL grammar and to handle 'now' as part of the TemporalLiteral class.

support 'now' in datetime parameter and in CQL filters

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/FeatureEncoderHtml.java

required to fix errors reported by the Google Search Console

remove duplicate "url" key from schema.org markup

---

ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ldproxy/ogcapi/features/geojson/domain/JsonSchema.java

This is required, e.g., for style metadata, which requires this capability with v3.1

de-serialization of JSON schemas

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/FeatureEncoderMVT.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/TilesQueriesHandlerImpl.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/domain/Tile.java

There was a bug that took a dataset (multi-collection) tile as a collection tile in an API with only a single collection.

fix distinction between dataset and collection tiles

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/TileFormatMVT.java

In feature queries for a vector tile, reduce the bounding box of the tile to the part of the tile with data. This avoids coordinate transformation issues with tiles at large scales and data that is stored in a regional, projected CRS.
closes #594

improve tile query

---

demo/vineyards/README.md

The link to DDL/DML results in a 404 Page not found. 
The proposed patch fixes this for the sql source files.

Fix links ending in 404 Page not found

---

ogcapi-draft/ogcapi-tiles/build.gradle

* version 1.3.16 references JTS 1.18.2 (note that ldproxy 3.2.1 already uses JTS 1.18.2 with version 1.3.15)
* remove redundant repository declaration

bump java-vector-tile dep to 1.3.16

---

ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/html/OgcApiCollectionView.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/html/OgcApiCollectionsView.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/domain/OgcApiCollection.java
ogcapi-stable/ogcapi-collections/src/main/resources/de/ii/ogcapi/collections/templates/collection.mustache
ogcapi-stable/ogcapi-collections/src/main/resources/de/ii/ogcapi/collections/templates/collections.mustache
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/CollectionExtensionFeatures.java
ogcapi-stable/ogcapi-foundation/src/main/resources/i18n-de.properties
ogcapi-stable/ogcapi-foundation/src/main/resources/i18n-en.properties

Where a count is set (and not negative) an "itemCount" member is added to the collection object in the extensions. It is also included in the HTML output.
closes #30 
@azahnen - I noticed that for more than half of the daraa collections, the value is set to -1, because of an exception when computing the count. For example, for CulturePnt. The exception is `org.postgresql.util.PSQLException: ERROR: variable not found in subplan target list`.

add itemCount to the Collection resources

---

build.gradle
ogcapi-draft/build.gradle
ogcapi-stable/build.gradle

The gradle plugin added a dependency with version `+`, which introduced a bug in master without a code change.
Since the new dynamic version did not a match another static dependency, starting ldproxy failed with `Module com.google.common` not found.
This PR removes the dynamic version and fixes the issue.

fix plugin deps

---

demo/vineyards/README.md

While replicating the demo, I noticed a broken link at [Step 4](https://github.com/interactive-instruments/ldproxy/tree/master/demo/vineyards#step-4-fine-tuning-the-api-configuration)

fix link to ogc_api.yml

---

ogcapi-draft/ogcapi-tiles/build.gradle

The maven repository of the java-vector-tile library was moved.

Update maven repo

---

ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/app/GmlWriterProperties.java

This PR also maps the values "t" and "1" reported in the feature stream in the case of a Boolean property to `true`. This reflects the behavior in other feature encoders.

GML: fix boolean properties

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileFormatMVT.java

Currently, vector tiles cannot be generated from data with 3D coordinates. This PR adds a fix.

Fix tile query for 3D data

---

ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/CollectionsDataHydrator.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/app/CommonDataHydrator.java

It can useful to include links into the API in the description of a API or collection. This requires support for replacing the "{serviceUrl}" template in the description to adapt to different deployment URLs.

support {serviceUrl} in API/collection descriptions

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/DefaultLinksGenerator.java

In "self" links, the "f" parameter should not be set, if there is no alternate encoding (and maybe also no parameter "f").

skip f parameter in self links, if there is no alternate link

---

ogcapi-draft/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/app/CityJsonWriterGeometry.java
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/domain/FeatureTransformationContextGml.java

Buildings in LoD2 should have boundary surfaces, but in practice some buildings may not have them. This PR makes the handling more robust by detecting and handling such cases.

improve handling of LoD2 buildings without a boundary surface

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/app/OgcApiEntity.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiMediaType.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/infra/rest/ContentNegotiationMediaTypeImpl.java
ogcapi-stable/ogcapi-foundation/src/test/groovy/de/ii/ogcapi/foundation/infra/rest/ContentNegotiationSpec.groovy

This PR makes content negotiation for the media type more robust. In particular, content negotiation now supports media type parameters. This PR is required, for example, for the GeoJSON compatibility mode of JSON-FG added by #758.

improve content negotiation

---

xtraplatform.gradle

The xtraplatform-spatial dependency was outdated to a branch (that has been merged) instead of master.

fix xtraplatform-spatial dependency

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileFormatMVT.java

Closes #709.
In FilterQuery we already use a buffer around the extent of the data to avoid unexpected behavior because of floating point issues in case of collections with a single point feature or when converting a bounding box to the native CRS. We also need this for tile queries.
Note that this is a PR again the `redesign-tiles` branch.

use buffer around the data bbox in tile queries

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiRequestContext.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/FoundationConfiguration.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/QueriesHandler.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/infra/rest/ApiRequestDispatcher.java

Large HTTP headers increase the size of the response and may cause an exception in dropwizard. This adds a `linkHeaderLengthLimit` option to omit the Link header, if the text length of the link is larger than the limit.
No default limit value is set for backwards compatibility. In version 4.0 we should consider to set a default limit.

Add option to omit large Link header

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleRepositoryFiles.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiMediaType.java

ApiMediaType::matches used content negotiation, but must just check compatibility, including parameters (which MediaType::isCompatible ignores). The target media type has already been negotiated.
This is a follow-up to #759. Before that pull request, the behaviour was stricter.
The pull request also improves a related error message.

fix ApiMediaType::matches

---

ogcapi-draft/ogcapi-maps/src/main/java/de/ii/ogcapi/maps/app/MapTileSetsFormatHtml.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesDataHydrator.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesHelper.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/html/TileSetsFormatHtml.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TileProviderMbtiles.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TileSetsView.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeatureCollectionView.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/MapClient.java
ogcapi-stable/ogcapi-html/src/main/resources/de/ii/ogcapi/html/templates/mapClient.mustache

Closes #779 
Tested with demo configurations plus in addition also a zoomstack API that provides no features, just tiles using the MBTiles file.
In cases where the API or collection has no associated spatial extent (e.g., an API with a MBTiles provider), the information for each tile matrix set was not passed to the HTML representation.
The initial view of a map is determined as follows: For feature views, always use the bounding box of the features. For tile views, the following sequence is used:
1. Use the style, if available, which will use the center/zoom specified in the style
2. Use center/zoom, if available (from the tileset, either from the configuration or from the MBTiles metadata)
3. …

Tile improvements

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeatureCollectionView.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeatureEncoderHtml.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeaturesFormatHtml.java

Previously transformations on geometry properties had no effect. This was fixed in #719. In the Features HTML representation, no map is shown when no geometry is present in the data. Since the bugfix, no map is now shown, if the Features HTML configuration included a transformation that removes the geometry property from the response. Such a transformation does not really make sense, but is present in some existing API configurations. To support those configurations, the behavior is changed to hide the map, if the feature schema (without transformations) includes a primary geometry property.

Features HTML: improve hideMap behavior

---

ogcapi-draft/ogcapi-crud/src/main/java/de/ii/ogcapi/crud/app/EndpointCrud.java
ogcapi-draft/ogcapi-filter/src/main/java/de/ii/ogcapi/filter/api/QueryParameterFilter.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileFormatJPEG.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileFormatMVT.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileFormatPNG.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileFormatTIFF.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/EndpointOpenApi.java

Several conformance class URIs included "req" in the path instead of "conf". Some of them were introduced in #802. In CRUD the "update" conformance class was not enabled.

fix conformance class URIs

---

ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/FeatureEncoderGltf.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/GltfBuildingBlock.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/domain/GltfConfiguration.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/domain/TriangleMesh.java
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/Cesium/index.jsx
ogcapi-stable/ogcapi-html/src/main/resources/de/ii/ogcapi/html/templates/data-cesium.mustache

Closes #939
I have tested the outline extension using [Cesium Sandcastle](https://sandcastle.cesium.com/) with a tile set provided by ldproxy.
Without outline (ldproxy Cesium client):
With outline (using Sandcastle):
Sandcastle code using `gebaeude` (LoD1):
```javascript
const viewer = new Cesium.Viewer("cesiumContainer", {});
const buildingsTileset = new Cesium.Cesium3DTileset({
url: 'data:application/json,%7B%22asset%22%3A%7B%22version%22%3A%221.1%22%2C%22generator%22%3A%22ldproxy%22%2C%22copyright%22%3A%22Bezirksregierung+K%C3%B6ln%2C+%3Ca+href%3D%5C%22http%3A%2F%2Fwww.geobasis.nrw.de%2F%5C%22+target%3D%5C%22_blank%5C%22%3EGeobasis+NRW%3C%2Fa%3E%22%7D%2C%22geometricError%22%3A10000.0%2C%22root% …
```

Add support for CESIUM_primitive_outline

---

ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/domain/Tiles3dConfiguration.java

The derived option must be ignored also in JSON serialization, not just in the documentation.

Fix incorrect use of @DocIgnore

---

ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointAdHocQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointStoredQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchBuildingBlock.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchQueriesHandlerImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/SearchQueriesHandler.java

This is a first step to address #906. The self, alternate and paging links are removed for ad-hoc queries.
The limitation that ad-hoc queries do not support paging has been documented as a limitation in the building block for now until this issue has been discussed in OGC. For now, use sufficiently large values for the limit parameter to avoid the need for paging.

Search: Remove links from responses to ad-hoc queries

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/QueryParameterBbox.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/QueryParameterDatetime.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeaturesCoreConfiguration.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesQueriesHandlerImpl.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesConfiguration.java
xtraplatform.gradle

- Fix regression: Title and description were not set for the tilesets in the tilesets metadata. In addition: removed unused vars and simplified code.
- improve featureType->collectionId mapping
- no ETag for HTML unless explicitly configured: This issue was probably already present in 3.3 as a result of the CRUD changes.
- Tiles: add default for center. Regression tests showed that previously there was a center value if a default level was specified, but no center - although I could not really find easily how/where that was computed. Nevertheless it seems reasonable to use the center of the extent as a fallback.
- IS NULL not supported by WFS provider. IS NULL is required to properly implement …

Edits from pre-release tests

---

ogcapi-custom/ogcapi-features-csv/src/main/java/de/ii/ogcapi/features/csv/app/FeaturesFormatCsv.java
ogcapi-custom/ogcapi-features-flatgeobuf/src/main/java/de/ii/ogcapi/features/flatgeobuf/app/FeaturesFormatFlatgeobuf.java

The problem was introduced in the Tiles redesign when `collectionId` was removed from `EncodingContextSfFlat` (in xtraplatform-spatial, which is unaware of the OGC API collection concept) and added to CSV and FGB modules - but without setting the value. It was set in the `transformationContext`, but 'invisible' since that was cast to `EncodingContextSfFlat`.

Fix error with SF Flat encodings

---

ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/QueryParametersStoredQueries.java
ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/app/QueryParametersQueryables.java

The query parameters for queryables and stored queries were considered applicable on all HTTP methods, not just GET. For example, the queryables query parameters were also available on the POST method to create a feature in the CRUD module.

Query parameters for queryables and stored queries only on GET requests

---

ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesLinkGenerator.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesOnCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesQueriesHandlerImpl.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/html/TileSetsView.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TileLayer.java
xtraplatform.gradle

Bugs:
- `geometryType` -> `geometryDimension`: Tileset metadata in the released standard uses `geometryDimension`, not any more `geometryType`. This was missed in the update to OGC API Tiles 1.0 / TMS 2.0. 
Bugs or Improvements (depends on discussions in the SWG):
- Add `tilesets-*` links on `/collections`: It was apparently the intention to require these links not only on each collection resource, but also if the collections are embedded in the collections array. 
Improvements:
- Improve tile geometry validity
- If a tile geometry is invalid, continue to try to fix it, but reduce the result again to the tile grid. Stop after two attempts.
- Small improvements 
- If determining a "full" tile …

Tiles: Address comments/issues from the OGC June 2023 Code Sprint

---

ogcapi-stable/ogcapi-html/src/main/javascript/.neutrinorc.js
ogcapi-stable/ogcapi-html/src/main/javascript/package.json
ogcapi-stable/ogcapi-html/src/main/javascript/src/apps/maplibre/index.jsx
ogcapi-stable/ogcapi-html/src/main/javascript/yarn.lock

Follow-up to #1015. 
By default the javascript build only supported the last 2 versions of each browser. This changes our default to [browserslist defaults](https://browsersl.ist/#q=defaults), which includes Firefox ESR, and adds `core-js` polyfills.

support firefox-esr

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/Configuration/index.jsx
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/styles.js

This is a follow-up to PR #1024 that added support for terrain in MapLibre styles. It turned out that for some reason, using a terrain in a default style led to JavaScript errors when displaying features with the derived style. This change removes terrains from the derived styles for the GeoJSON features.
In addition, hillshade and background layers were not properly handled when a style for the GeoJSON features were derived for displaying feature(s) in the HTML representation.

fix issues in the derived style for feature(s)

---

ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/QueryParameterF.java

`EndpointExtenson.getMediaTypes()` excludes these (internal) formats, e.g., `pap`. However, currently `pap` is included in the list of values in the `f` parameter for features, but it is not a supported media type in the API.

exclude formats with getContent()=null from f

---

ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetMultiCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetSingleCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetsMultiCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetsSingleCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileSeedingBackgroundTask.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesOnCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesOnLandingPage.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/PathParameterTileMatrixSetId.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TileFormatExtension.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TileGenerationUserParameter.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesConfiguration.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesMigrationV4.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/infra/EndpointTileMultiCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/infra/EndpointTileSingleCollection.java

Closes #1005.
If a tile provider exists, the provider is used to determine, which tilesets exist. Otherwise the deprecated options are used (until v4).

Tiles: deprecate datasetTiles, collectionTiles

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/TypedQueryParameter.java

This is a follow-up to #1072, which did not properly handle the case, where no value was provided for a parameter in the request.

typed query parameters: fix handling default values

---

ogcapi-stable/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/app/CityJsonWriterFeature.java
ogcapi-stable/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/domain/CityJsonConfiguration.java

Currently the CityJSON module requires that every building part has a unique "id" property. If not, an exception is thrown when a building part is encountered. Strictly, it is not necessary that the id must be persistent across requests. From an API perspective, it is sufficient, if the building ids are persistent. This change generates a UUID as the identified, if no id is provided for a building part, instead of throwing an error.

relax requirement for a persistent ID for building parts

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleRepositoryFiles.java

This is a follow-up to #1087, which has disabled that styles in `other-styles` could be associated with a collection. This change enables this capability again, which is needed. See, e.g., `zoomstack` or `cologne_lod2`.

reenable support for collection styles

---

ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/Migrations.java
ogcapi-custom/ogcapi-resources/src/main/java/de/ii/ogcapi/resources/app/StylesMigrationV4.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StylesConfiguration.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/domain/FeaturesHtmlConfiguration.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetMultiCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesConfiguration.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesMigrationV4.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/infra/EndpointTileSetMultiCollection.java

Properly migrate the following deprecated configuration properties for v4:
- TilesConfiguration.getCollectionTiles
- TilesConfiguration.getDatasetTiles
- StylesConfiguration.getResourcesEnabled
- StylesConfiguration.getResourceManagerEnabled
- StylesConfiguration.getDefaultStyle
@azahnen - please check

Fix deprecated properties

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/domain/FeaturesView.java

It is unclear why ISO 8859-1 is currently expected, but the current Apache HTTP Client uses UTF-8 as the default encoding. This may have been different in previous versions.
Closes #1120

URIs are encoded in UTF-8

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreBuildingBlock.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/QueryParameterBbox.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/QueryParameterDatetime.java

Closes #1157.
Closes #1099.
Strictly, this is not a bug fix, but it should be included in v3.6.2. It is a workaround for using `bbox` and `datetime` with large datasets.

improve bbox/datetime for required properties

---

ogcapi-draft/ogcapi-filter/src/main/java/de/ii/ogcapi/filter/api/QueryParameterFilter.java
ogcapi-draft/ogcapi-filter/src/main/java/de/ii/ogcapi/filter/api/QueryParameterFilterLang.java
ogcapi-draft/ogcapi-filter/src/main/java/de/ii/ogcapi/filter/app/FilterBuildingBlock.java
ogcapi-draft/ogcapi-filter/src/test/groovy/de/ii/ogcapi/filter/FilterParameterSpecification.groovy
ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/domain/Subtree.java
ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/domain/TileResourceDescriptor.java
ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/app/QueryablesBuildingBlock.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/QueryParameterBbox.java
xtraplatform.gradle

Closes #599. If there are any additional changes in the approval process, we will create a new issue and PR.
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/268.
ANTLR does not support the range `\u10000` to `\u10FFFF`, at least this is what is reported as an error, if a one of those characters is included in the lexer. According to the [documentation](https://github.com/antlr/antlr4/blob/dev/doc/unicode.md), the currently used version of ANTLR should support these characters, but this does not seem to be the case. In practice, this was no issue so far.

CQL2: update to release candidate

---

demo/vineyards/README.md
ogcapi-draft/ogcapi-crud/src/test/groovy/de/ii/ogcapi/crud/TransactionalRESTApiSpec.groovy
ogcapi-draft/ogcapi-filter/build.gradle
ogcapi-draft/ogcapi-styles/src/test/groovy/de/ii/ogcapi/styles/app/StylesManagerRESTApiSpec.groovy
ogcapi-draft/ogcapi-styles/src/test/groovy/de/ii/ogcapi/styles/app/StylesRESTApiSpec.groovy
ogcapi-draft/ogcapi-styles/src/test/groovy/de/ii/ogcapi/styles/app/StylesRepresentationRESTApiSpec.groovy
ogcapi-stable/ogcapi-features-core/src/test/groovy/de/ii/ogcapi/features/core/OgcApiCoreRestApiSpec.groovy
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/AbstractRequestContext.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiCatalogProvider.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiRequestContext.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/URICustomizer.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/infra/rest/ExceptionMapper.java
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/stories.jsx
ogcapi-stable/ogcapi-tiles/src/test/groovy/de/ii/ogcapi/tiles/TilesRESTApiSpec.groovy
xtraplatform.gradle

Closes #1190 .
Depends on interactive-instruments/xtraplatform#160.
Traefik can be used to test that using a reverse proxy to change the path still works as expected:
```yml
version: "3.3"
services:
traefik:
image: "traefik:v2.11"
command:
- "--providers.docker=true"
- "--entrypoints.web.address=:7080"
ports:
- "7080:7080"
volumes:
- "/var/run/docker.sock:/var/run/docker.sock:ro"
ldproxy:
image: "docker.ci.interactive-instruments.de/iide/ldproxy:root-path"
environment:
- EXTERNAL_URL="http://localhost:7080/foo/bar" 
- DB_HOST=host.docker.internal:5432
volumes:
- /path/to/configs-ldproxy/xleit:/ldproxy/data
labels:
- traefik.http.services.ldp.loadbalancer.server.port=7080
- …
```

change services endpoint path to root

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ChangingSpatialExtent.java

If a changing spatial extent is updated, it is stored as a CRS84 extent. If the data is 3D, the extent must be a CRS84h extent, otherwise the next update will fail, because the delta extent is in CRS84h, but the cached extent is in CRS84.

maintain CRS dimension in cached spatial extents

---

ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesQueriesHandlerImpl.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/OwsAddress.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/OwsContact.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/OwsResponsibleParty.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/OwsServiceProvider.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/OwsTelephone.java

The WMTS Capabilities contained only minimal Service Provider information in the Capabilities document (provider name and site). This pull request adds additional elements where that data is available for the API: contact name, email and telephone.

additional metadata in the WMTS ServiceProvider

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/domain/FeatureEncoderHtml.java

Closes #1294. Before rendering, derive an immutable view from the modifiable view to leverage the "derive" annotations in the evaluation.

render immutable view

---

ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/LdproxyCfgImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointParameter.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointParameters.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointStoredQueriesManager.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointStoredQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointStoredQueryDefinition.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/QueryParameterOffsetStoredQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchBuildingBlock.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchQueriesHandlerImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/StoredQueryExpressionFactory.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/StoredQueryFormatJson.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/StoredQueryRepositoryImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/QueryExpression.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/QueryExpressionQueryParameter.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/SearchQueriesHandler.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/SingleQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/SingleQueryWithParameters.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/StoredQueryExpression.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/StoredQueryFormat.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/StoredQueryRepository.java

Currently, parameters are only supported in filter expressions in a stored query. Parameters are also useful in other members of a query expression, e.g. the CRS information, the limit value or the profiles to apply.
This commit supports the use of parameters in all members of the query expression of a stored query, except "id", "title", "description", and "offset".
A new immutable `StoredQueryExpression` is introduced that supports parameter objects in the values of the query expression of a stored query. These instances are what is stored as values. The `QueryExpression` is simplified to remove all support for parameters.
Example of the use of parameters in "crs" and "profiles":
```
...,
"crs": …
```

Generally support parameters in stored queries - not only in filters

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/Configuration/popup.js

Closes #1367.
The HTML view of features also maps URLs of PNG/JPEG images to `<img>` elements to directly display the image. I decided not to include this behavior in the popup since images may be too large for a popup.

MapLibre popups: render HTTP URLs as clickable links

---

ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/FeatureEncoderGltf.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/StateGltf.java

Closes #1358.
These changes join nodes/meshes/primitives to significantly reduce the number of drawing calls.
Additional improvements could be implemented, e.g., reordering of triangles for improved GPU performance or transmission size, compression, simplification of triangles, etc.

Reduce number of glTF drawing calls

---

ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/FeatureEncoderGltf.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/domain/TriangleMesh.java
ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/domain/TileResourceDescriptor.java

This Pull Request includes the following improvements or bugfixes: 
- 3D Tiles: A building that crosses tile boundaries has been included in all tiles that it intersects, which increases the overall payload and results in rendering artefacts in those buildings. A building is now included in only one tile - the northwestern-most tile that the building intersects.
- glTF: The earcut4j library sometimes creates incorrect triangulation results (e.g., triangles are created that go beyond the polygon). The JTS triangulation seems to produce better results. It is a bit slower and is not always able to compute the triangles. The changed code first tries the `ConstrainedDelaunayTriangulator` from JTS and …

Improve 3D Tiles

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/FilterEditor/Editor/Spatial/util.js

Check that a value is set before accessing the bounding box.
Closes #1395

Filter Editor: 'spatial' bbox is optional

---

gradle/layers.versions.toml
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterPlace.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/domain/JsonFgGeometryType.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/GeoJsonWriterGeometry.java

In the writers for "geometry" and "place" detect unsupported geometries. Write a `null` geometry instead and add a log for the first instance of an unsupported geometry type.
JSON-FG geometry types: Remove GENERIC (unused), map GEOMETRY_COLLECTION and add new method `isSupported()`.
Depends on https://github.com/ldproxy/xtraplatform-spatial/pull/363
Closes #1413

GeoJSON/JSON-FG: handle unsupported geometries
