ldproxy-service/src/main/resources/de/ii/ldproxy/output/html/property.mustache
ldproxy-service/src/main/resources/de/ii/ldproxy/output/html/propertySub.mustache

add missing =

---

xtraplatform.gradle

See interactive-instruments/ldproxy-project-management#43

cql nested filters

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TileGeneratorJson.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesEndpoint.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesQuery.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesQueryImpl.java
xtraplatform.gradle

Fixes interactive-instruments/ldproxy-project-management#52. All 4 examples should work now.

Fix spatial filters

---

build.gradle
composite/settings.gradle
docker.gradle
ldproxy-service-legacy-migration/src/main/java/de/ii/ldproxy/service/migration/Wfs3ServiceMigrate.java
ldproxy-wfs3/src/main/java/de/ii/ldproxy/wfs3/generator/Wfs3ServiceGenerator.java
ogcapi-draft/ogcapi-crs/src/main/java/de/ii/ldproxy/wfs3/crs/CrsSupport.java
ogcapi-draft/ogcapi-crs/src/main/java/de/ii/ldproxy/wfs3/crs/CrsSupportImpl.java
ogcapi-draft/ogcapi-crs/src/main/java/de/ii/ldproxy/wfs3/crs/OgcApiCollectionCrs.java
ogcapi-draft/ogcapi-html/src/main/java/de/ii/ldproxy/target/html/FeatureTransformerHtml.java
ogcapi-draft/ogcapi-html/src/main/java/de/ii/ldproxy/target/html/FeatureTransformerHtmlComplexObjects.java
ogcapi-draft/ogcapi-migrations/src/main/java/de/ii/ldproxy/ogcapi/migrations/OgcApiApiMigrationV1V2.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TileGeneratorJson.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/application/OgcApiApiEntity.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/domain/OgcApiApiDataV2.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/infra/persistence/OgcApiDatasetHydrator.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/api/OgcApiFeatureCoreDataHydrator.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesCoreProvidersImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesQuery.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/application/OgcApiFeaturesQueryImpl.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ldproxy/target/geojson/FeatureTransformerGeoJson.java
xtraplatform.gradle

closes interactive-instruments/ldproxy-project-management#19

auto service generation

---

docs/dev/exceptions.md

doc: exceptions

---

ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/ObservationProcessingQueriesHandlerImpl.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/parameters/PathParameterCollectionIdProcess.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TileFormatMVT.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TileSetFormatTileJson.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TilesQueriesHandlerImpl.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/VectorTileSeeding.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesQueryImpl.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ldproxy/ogcapi/features/geojson/domain/SchemaGeneratorFeature.java

check for featureType before using collectionId

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/VectorTileSeeding.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/app/OgcApiEntity.java

only start each startup task once

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TilesQueriesHandlerImpl.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/app/BackgroundTaskExceptionHandlerImpl.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/infra/rest/ExceptionMapper.java

improve error logging

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/FeatureTransformerTilesMVT.java

support remove transformations for vector tiles

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ldproxy/ogcapi/styles/app/EndpointStyle.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ldproxy/ogcapi/styles/app/EndpointStyleMetadata.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ldproxy/ogcapi/styles/app/EndpointStyles.java

support styles without explicit metadata

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/TilesQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/QueriesHandler.java

return 404, if the result is empty in a Feature request

---

ogcapi-draft/ogcapi-projections/src/main/java/de/ii/ldproxy/ogcapi/projections/QueryParameterSkipGeometry.java
xtraplatform.gradle

add query parameter skipGeometry

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/FeatureTransformerHtml.java

changed to be consistent with GeoJSON behaviour; closes #273

handle dimension=null

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/OgcApiDataV2.java

This is an addition to PR #329, see https://github.com/interactive-instruments/ldproxy/pull/329#issuecomment-734849435 for background. The change merges spatial and temporal extents separately.

Add temporal extent computations, part 2

---

docs/de/configuration/services/building-blocks/features-html.md
docs/de/configuration/services/building-blocks/general-rules.md
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/FeatureTransformerHtml.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/FeatureTransformerHtmlComplexObjects.java

support string template filters in itemLabelFormat

---

version.gradle
xtraplatform.gradle

Fix string templates

---

ldproxy-product/src/main/java/de/ii/ldproxy/product/MustacheResolverLdproxy.java
ldproxy-product/src/main/java/de/ii/ldproxy/product/Wfs3ServiceMigrate.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ldproxy/ogcapi/collections/domain/OgcApiCollection.java

closes #373
also avoid gradle license exception

remove nativeCrs/nativeCrsCoordinateEpoch

---

ldproxy-product/src/main/java/de/ii/ldproxy/product/MustacheResolverLdproxy.java
ldproxy-product/src/main/java/de/ii/ldproxy/product/Wfs3ServiceMigrate.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/CollectionExtensionFeatures.java

no extent, if no spatial and temporal queryable

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/domain/SchemaGeneratorFeatureOpenApi.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ldproxy/ogcapi/features/geojson/domain/SchemaGeneratorFeatureGeoJson.java

integer enums in schemas result in NPE

---

docs/de/configuration/services/building-blocks/README.md
docs/de/configuration/services/building-blocks/sorting.md
ogcapi-draft/ogcapi-geometry-simplification/src/main/java/de/ii/ldproxy/ogcapi/geometry_simplification/QueryParameterMaxAllowableOffsetFeatures.java
ogcapi-draft/ogcapi-projections/src/main/java/de/ii/ldproxy/ogcapi/projections/QueryParameterProperties.java
ogcapi-draft/ogcapi-projections/src/main/java/de/ii/ldproxy/ogcapi/projections/QueryParameterSkipGeometry.java
ogcapi-draft/ogcapi-sorting/build.gradle
ogcapi-draft/ogcapi-sorting/src/main/java/de/ii/ldproxy/ogcapi/sorting/CapabilitySorting.java
ogcapi-draft/ogcapi-sorting/src/main/java/de/ii/ldproxy/ogcapi/sorting/JacksonSubTypeIdsSorting.java
ogcapi-draft/ogcapi-sorting/src/main/java/de/ii/ldproxy/ogcapi/sorting/QueryParameterSortbyFeatures.java
ogcapi-draft/ogcapi-sorting/src/main/java/de/ii/ldproxy/ogcapi/sorting/SortingConfiguration.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetSingleCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetsMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSetsSingleCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSingleCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/Tile.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/ETRS89_UTM32_NRW.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/EndpointTileMatrixSets.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/TileMatrixSet.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/WebMercatorQuad.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/WorldCRS84Quad.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/tileMatrixSet/WorldMercatorWGS84Quad.java
ogcapi-draft/ogcapi-tiles/src/test/groovy/de/ii/ldproxy/ogcapi/tiles/TileSeedingSpec.groovy
ogcapi-stable/ogcapi-common/src/test/groovy/de/ii/ldproxy/ogcapi/LandingPageSpec.groovy
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ldproxy/ogcapi/crs/app/QueryParameterBboxCrsFeatures.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ldproxy/ogcapi/crs/app/QueryParameterCrsFeatures.java
ogcapi-stable/ogcapi-features-core/src/test/groovy/de/ii/ldproxy/ogcapi/features/core/OgcApiCoreSpecCollections.groovy
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/OgcApiDataV2.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/TemporalExtent.java

Fixes #381.
Fixes #371.
Closes #217.
Prepares for interactive-instruments/ldproxy-project-management#41.

Fixes and sort keys

---

ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ldproxy/ogcapi/oas30/app/ExtendableOpenApiDefinition.java

no info.license object without a name

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/EndpointFeatures.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/QueryParameterLimitFeatures.java

accept limit values greater than the maximum value

---

ogcapi-draft/ogcapi-collections-queryables/src/main/java/de/ii/ldproxy/ogcapi/collections/queryables/app/EndpointQueryables.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ldproxy/ogcapi/collections/schema/EndpointSchema.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/EndpointDapa.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/EndpointObservationProcessing.java
ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/EndpointVariables.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileSingleCollection.java
ogcapi-draft/ogcapi-transactional/src/main/java/de/ii/ldproxy/ogcapi/features/transactional/CommandHandlerTransactional.java
ogcapi-draft/ogcapi-transactional/src/main/java/de/ii/ldproxy/ogcapi/features/transactional/EndpointTransactional.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ldproxy/ogcapi/collections/infra/EndpointCollection.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ldproxy/ogcapi/collections/infra/EndpointCollections.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/common/infra/EndpointLandingPage.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/EndpointFeatures.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/app/OgcApiDataV2Defaults.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/ApiEndpointDefinition.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ldproxy/ogcapi/oas30/app/ExtendableOpenApiDefinition.java

Transactions

---

ogcapi-stable/ogcapi-common/src/main/java/de/ii/ldproxy/ogcapi/common/domain/OgcApiExtentTemporal.java

closes #409
this pull request replaces #410 and just applies the temporal filter change in ldproxy, separate from the pull request #406

Temporal filtering improvements

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/FeatureTransformerHtmlComplexObjects.java

COMPLEX_OBJECTS layout and WFS provider

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/EndpointTileMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/VectorTileSeeding.java

Closes #429.
@cportele Can you check if this makes sense and if there are more places where this would be needed?

fix tile seeding

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/app/FeaturesCoreDataHydrator.java

fix bug (feature collections cannot be disabled)

---

ogcapi-stable/ogcapi-features-html/src/main/resources/templates/property.mustache

HTML: reactivate image URL handling

---

xtraplatform.gradle

WFS improvements and bugfixes

---

ogcapi-draft/ogcapi-filter/src/main/java/de/ii/ldproxy/ogcapi/filter/api/QueryParameterFilter.java
ogcapi-draft/ogcapi-filter/src/test/groovy/de/ii/ldproxy/ogcapi/filter/FilterParameterSpecification.groovy

See https://github.com/interactive-instruments/xtraplatform-spatial/pull/76

add tests for array predicates

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/domain/EndpointExtension.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ldproxy/ogcapi/infra/rest/ContentNegotiation.java

catch exceptions due to invalid headers during content negotiation

---

ogcapi-draft/ogcapi-filter/src/test/groovy/de/ii/ldproxy/ogcapi/filter/FilterParameterSpecification.groovy

Tests for https://github.com/interactive-instruments/xtraplatform-spatial/pull/81

unit tests for nested CQL filters

---

ogcapi-stable/ogcapi-common/src/main/resources/templates/exception.mustache

urlPrefix not available in HTML exceptions

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/FeatureMVT.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ldproxy/ogcapi/features/core/domain/SchemaGeneratorFeatureOpenApi.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ldproxy/ogcapi/features/geojson/app/GeoJsonWriterGeometry.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/FeatureHtml.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ldproxy/ogcapi/features/html/app/PropertyHtml.java
xtraplatform.gradle

- fixes missing default transformer for DATE
- fixes issues with nested queryables

Transformation fixes

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/PurgeTileCacheTask.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/TileProviderFeatures.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/app/tileMatrixSet/TileMatrixSetRepositoryImpl.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/domain/SeedingOptions.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/domain/TilesConfiguration.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/infra/VectorTileSeeding.java
xtraplatform.gradle

Seeding options

---

ogcapi-draft/ogcapi-filter/src/main/java/de/ii/ldproxy/ogcapi/filter/api/QueryParameterFilterCrs.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ldproxy/ogcapi/crs/app/QueryParameterBboxCrsFeatures.java

in general, support for 3D needs to be improved in filters -> follow-up task

fix filter-crs and bbox-crs for 3D cases

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/api/AbstractEndpointTileSetMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ldproxy/ogcapi/tiles/api/AbstractEndpointTileSetSingleCollection.java

fix tile set endpoints

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/CollectionPropertiesQueriesHandlerImpl.java

content disposition filename should be lower case

---

ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/app/QueriesHandlerCommonImpl.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/OgcApiDatasetView.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/OgcApiExtent.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/OgcApiExtentSpatial.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/OgcApiExtentTemporal.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/CapabilityFeaturesCore.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/CollectionExtensionFeatures.java
xtraplatform.gradle

* also convert OgcApiExtent to immutables
* builds on https://github.com/interactive-instruments/xtraplatform-spatial/pull/119
* closes https://github.com/interactive-instruments/ldproxy/issues/655

support for 3D bounding boxes

---

ogcapi-draft/ogcapi-features-custom-extensions/src/main/java/de/ii/ogcapi/features/custom/extensions/infra/infra/EndpointPostOnItems.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesBuildingBlock.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/QueryParameterF.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/EndpointFeatures.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesQueryImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeaturesQuery.java

Fix issues identified by the CITE tests

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesQueryImpl.java

-   [x] Updated documentation (nothing to update, internal changes only)
Align with changes in https://github.com/interactive-instruments/xtraplatform-spatial/pull/122

update datetime mapping to CQL2

---

ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/DatasetView.java

fix paging with filters

---

.woodpecker/release.yml
.woodpecker/snapshot.yml
docker.gradle
docs.gradle
ldproxy-manager/build.gradle
ldproxy-manager/src/main/javascript/yarn.lock
ogcapi-stable/ogcapi-html/build.gradle

Support builds on Apple Silicon.

Apple silicon

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileMultiCollection.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileProviderFeatures.java

-   [ ] Added/updated unit tests (n/a)
-   [ ] Updated documentation (n/a)
Closes #674

TILES: Null Pointer Exception, if no spatial queryable is configured

---

ldproxy-cfg/build.gradle
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppContextCfg.java
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/LdproxyCfg.java
version.gradle

Unmerged fixes

---

ogcapi-draft/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/app/CityJsonBuildingBlock.java
ogcapi-draft/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/app/CityJsonWriterGeometry.java

-   [ ] All checks are passing
* Moves relative origin to the center of the bounding box of the data instead of the lower left corner
* Update documentation to state that v1.0 is supported, too

CityJSON improvements

---

ogcapi-stable/ogcapi-common/src/main/javascript/src/i18n/services_ogc_api.json

fix tooltips

---

ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/GeoJsonWriterProperties.java

-   [ ] All checks are passing
Closes #701

GeoJSON: always write a 'properties' member

---

ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/PropertyHtml.java
ogcapi-stable/ogcapi-features-html/src/main/resources/de/ii/ogcapi/features/html/templates/property.mustache

fix html escaping

---

ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/JacksonSubTypeIdsTextSearch.java
ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/PathParameterCollectionIdTextSearch.java
ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/QueryParameterQ.java
ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/TextSearchBuildingBlock.java
ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/domain/TextSearchConfiguration.java
ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/domain/package-info.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/EndpointFeatures.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreBuildingBlock.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesQueryImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeaturesCollectionQueryables.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeaturesCoreConfiguration.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeaturesFormatHtml.java

text search module

---

ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/DatasetView.java

decode query parameters with UTF-8

---

ogcapi-draft/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/app/FeaturesFormatCityJsonBase.java
ogcapi-draft/ogcapi-features-flatgeobuf/src/main/java/de/ii/ogcapi/features/flatgeobuf/app/FeatureEncoderFlatgeobuf.java
ogcapi-draft/ogcapi-features-json-fg/src/main/java/de/ii/ogcapi/features/json/fg/app/FeaturesFormatJsonFg.java
ogcapi-draft/ogcapi-features-json-fg/src/test/groovy/de/ii/ogcapi/features/json/fg/app/JsonFgWriterSetupUtil.groovy
ogcapi-draft/ogcapi-routes/src/main/java/de/ii/ogcapi/routes/app/QueryHandlerRoutesImpl.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/FeatureEncoderMVT.java
ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesQueriesHandlerImpl.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/OgcApiDatasetView.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/QueryParameterF.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeatureFormatExtension.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeatureTransformationContext.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/JsonSchema.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/FeaturesFormatGeoJson.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/GeoJsonWriterId.java
ogcapi-stable/ogcapi-features-geojson/src/test/groovy/de/ii/ogcapi/features/geojson/app/GeoJsonWriterSetupUtil.groovy
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/app/GmlWriterProperties.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeaturesFormatHtml.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiEndpointDefinition.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/Link.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ParameterExtension.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/infra/json/ClassSchemaCacheImpl.java

- closes #753
- closes #750
- closes #751
- closes #752
- add default value to JSON Schema class
- other minor edits
- includes also changes from PR #748

Prepare for Search building block

---

ogcapi-draft/ogcapi-features-flatgeobuf/build.gradle
ogcapi-draft/ogcapi-tiles/build.gradle
ogcapi-stable/ogcapi-features-core/build.gradle
ogcapi-stable/ogcapi-foundation/build.gradle

upgrade dependencies (jts, flatgeobuf, java-vector-tile, json-schema-validator)

---

ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppContextCfg.java

- Adjustments for xtraplatform changes

Fix cfg lib

---

ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppConfigurationCfg.java
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppContextCfg.java
ldproxy-manager/src/main/java/de/ii/ldproxy/manager/app/StaticResourcesManager.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/ExtendableOpenApiDefinitionImpl.java
xtraplatform.gradle

Adjust to xtraplatform changes.

adjust to xtraplatform changes

---

ogcapi-draft/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesBuildingBlock.java

zoomLevelsCache can be used to reduce the levels for which tiles are cached. If the option is not set for a tiling scheme, then tiles are cached at all levels. This changes uses getZoomLevelsDerived as the default, but in the presence of getZoomLevelsCacheDerived that range is used. Seeded levels are excluded. The assumption is that only higher levels are not seeded, if seeding is used.

Use zoomLevelsCache

---

ogcapi-draft/ogcapi-routes/src/main/java/de/ii/ogcapi/routes/app/html/RoutesFormatHtml.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleMetadataFormatHtml.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/app/html/CommonFormatHtml.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/DefaultLinksGenerator.java
xtraplatform.gradle

Fixes after testing:
* normalize use of f parameter
* restore support for the datetime parameter for WFS providers

Additional fixes after testing

---

ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/domain/CollectionsFormatExtension.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/app/QueryParameterBboxCrsFeatures.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/app/QueryParameterCrsFeatures.java
ogcapi-stable/ogcapi-features-core/build.gradle
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCore.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/EndpointOpenApi.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/OpenApiDefinition.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/OpenApiFile.java
ogcapi-stable/ogcapi-tiles/build.gradle
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/QueryParameterDatetimeTile.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesConformance.java

In some cases, the conformance declaration included conformance classes that were not enabled for an API.

Fix conformance declaration

---

ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/app/FeaturesFormatGml.java
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/app/GmlWriterSkeleton.java
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/domain/GmlConfiguration.java

fix schemaLocation edge cases

---

.grenrc.yml
.woodpecker/release.yml
CHANGELOG.md
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeatureCollectionView.java

Merge changes from v3.3.2:
- changelog
- changelog generation improvements
- fix for filter editor fields order

Merge 3.3.2

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/CollectionExtensionFeatures.java
ogcapi-stable/ogcapi-features-core/src/test/groovy/de/ii/ogcapi/features/core/OgcApiCoreSpecCollections.groovy

Fix missing collection extents

---

ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/xml/OgcApiCollectionXml.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/xml/OgcApiCollectionsXml.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/xml/OgcApiExtentXml.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/domain/CollectionsFormatExtension.java

Fix issues in Feature Collections

---

ogcapi-stable/ogcapi-html/src/main/resources/de/ii/ogcapi/html/templates/exception.mustache

Escape error details in HTML

---

build.gradle
composite/build.gradle
ogcapi-custom/build.gradle
ogcapi-draft/build.gradle
ogcapi-stable/build.gradle

upgrade base image

---

version.gradle
xtraplatform.gradle

upgrade xtraplatform, bump version

---

.woodpecker/check.yml
.woodpecker/release.yml
.woodpecker/scs.yml
.woodpecker/snapshot.yml
build.gradle
catalog.gradle
catalog.versions.toml
composite/build.gradle
composite/gradle/wrapper/gradle-wrapper.properties
composite/settings.gradle
gradle/wrapper/gradle-wrapper.properties
ldproxy-manager/build.gradle
ogcapi-custom/build.gradle
ogcapi-custom/gradle/wrapper/gradle-wrapper.properties
ogcapi-custom/settings.gradle
ogcapi-draft/build.gradle
ogcapi-draft/gradle/wrapper/gradle-wrapper.properties
ogcapi-draft/settings.gradle
ogcapi-stable/build.gradle
ogcapi-stable/gradle/wrapper/gradle-wrapper.properties
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ObjectSchema.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/PageRepresentation.java
ogcapi-stable/settings.gradle
settings.gradle

Sboms and deps

---

composite/settings.gradle
xtraplatform.gradle

- enables java17 compatibility for development environments

optional plugins import in composite build

---

ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/FeatureEncoderGltf.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/FeaturesFormatGltfBinary.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/domain/FeaturesFormatJsonFgBase.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/FeaturesFormatGeoJson.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/HeaderItems.java

The exception was introduced in #901 when the request is for a single feature.

Fix null pointer exception when extracting numberMatched

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/FilterEditor/util.js

Pull request #912 removed support for datasets with 3D coordinates. This change restores support for such datasets.

Support 3D data in filter editor

---

ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/HtmlConfiguration.java

Fixes issues in the documentation of the HTML building block.

Fix documentation

---

ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/app/CrsBuildingBlock.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/app/CrsOnCollection.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/app/CrsOnCollections.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/app/CrsSupportImpl.java
ogcapi-stable/ogcapi-crs/src/main/java/de/ii/ogcapi/crs/domain/CrsConfiguration.java

Add option to suppress global CRS list

---

ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/CollectionsOnLandingPage.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/html/CollectionsFormatHtml.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/app/HtmlBuildingBlock.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/HtmlConfiguration.java

Add option to suppress empty collections in the HTML page for the Feature Collections

---

ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/MeshSurfaceList.java
ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/PropertyGltf.java

Handle empty mesh

---

ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchBuildingBlock.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchQueriesHandlerImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/QueryExpression.java

Search: add filterCrs

---

ogcapi-stable/ogcapi-foundation/src/main/resources/i18n-de.properties
ogcapi-stable/ogcapi-foundation/src/main/resources/i18n-en.properties

Updates a link in a link title.

Fix link in documentation

---

ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesBuildingBlock.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/domain/TilesMigrationV4.java

extract tiles migration

---

src/markdown/docs/de/advanced/specifications.md
src/markdown/docs/en/advanced/specifications.md

-   [ ] All checks are passing
Fix a broken link in the specifications page.

Fix broken link

---

ogcapi-draft/ogcapi-features-gltf/src/main/java/de/ii/ogcapi/features/gltf/app/FeaturesFormatGltfBinary.java

Move the CRS transformer request from the glTF-binary format constructor to the `onStartup()` method. This will also only raise an issue, if the API extension is actually used by some API.
Closes #985.

Improve stability during startup

---

ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/app/QueriesHandler3dTilesImpl.java
ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/app/Seeding.java
ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/infra/Endpoint3dTilesContent.java

Close streams of 3D Tiles content/subtree resources

---

ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesBuildingBlock.java

Tiles: validate only collections that are enabled

---

ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterCrs.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterDescribedby.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterFeatureType.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterGeometryDimension.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterLinks.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterPlace.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterTime.java
ogcapi-draft/ogcapi-features-jsonfg/src/test/groovy/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterCrsSpec.groovy

This PR updates to JSON-FG writers to support multi-collection queries.
Closes #1009.

Update JSON-FG to support SEARCH

---

ogcapi-stable/ogcapi-html/src/main/javascript/package.json
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/Configuration/index.jsx
ogcapi-stable/ogcapi-html/src/main/javascript/yarn.lock

Closes #980.
@cportele Let me know if you still have issues.

upgrade to maplibre 3.2.1

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/MbStyleStylesheet.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/MbStyleTerrain.java

add support for terrain in MapLibre styles

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StylesBuildingBlock.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StylesConfiguration.java

add documentation for the layer control dialog

---

build.gradle
catalog.versions.toml

upgrade docker base image to `eclipse-temurin:17-jre`

---

ogcapi-draft/ogcapi-crud/src/main/java/de/ii/ogcapi/crud/app/CrudBuildingBlock.java
xtraplatform.gradle

Closes #1079 
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/230.

limit transaction support to PGIS providers

---

ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/ExtendableOpenApiDefinitionImpl.java

Closes #1097.
Thanks @schmity.

fix typo in API definition

---

ogcapi-draft/ogcapi-routes/src/main/java/de/ii/ogcapi/routes/app/RouteRepositoryFiles.java
xtraplatform.gradle

Depends on interactive-instruments/xtraplatform#148.

fix routes storage

---

ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/app/QueryablesBuildingBlock.java

Updates the documentation of the Queryables module to align with the implementation and to discuss limitations.
See also https://github.com/interactive-instruments/xtraplatform-spatial/pull/236.

update Queryables documentation

---

README.md
src/markdown/docs/de/README.md
src/markdown/docs/en/README.md

This PR adds the introduction page in English, too, and slightly updates the text.
See also https://github.com/interactive-instruments/xtraplatform-spatial/pull/255, which adds documentation for schema constraints in English.

add missing English documentation

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/FeatureFormatExtension.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeaturesFormatHtml.java
xtraplatform.gradle

Closes #1139
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/254

ignore feature references with id=null

---

ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/app/FeaturesFormatGml.java
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/app/GmlWriterGeometry.java
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/domain/FeatureTransformationContextGml.java
ogcapi-stable/ogcapi-features-gml/src/main/java/de/ii/ogcapi/features/gml/domain/GmlConfiguration.java

add option 'gmlIdOnGeometries'

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/Endpoint.java

avoid unnecessary generation of endpoint definitions

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/LayerControl/LegendSymbol/Fill.js
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/LayerControl/LegendSymbol/main.js

fix fill-pattern and pixelRatio

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/Configuration/index.jsx

add popup for custom styles

---

ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/GeoJsonWriterProperties.java
xtraplatform.gradle

Closes #1180.
See https://interactive-instruments-ldproxy-pr-1181.surge.sh/providers/details/transformations.html.
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/267.

null values

---

gradle/libs.versions.toml

Closes #1183.
Closes #1184.
Closes #1185.
Closes #1186.
Closes #1187.
Closes #1188.

upgrade deps

---

ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/QueryParameterQ.java
ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/TextSearchBuildingBlock.java

Closes #1202
Documentation: An outdated limitation is also removed, the comparison is case-insensitive.

Fix text search

---

ogcapi-draft/ogcapi-text-search/src/main/java/de/ii/ogcapi/text/search/app/QueryParameterQ.java

Follow-up to #1203. In that PR, the reference to the case limitation was only removed in the API definition, not in the ldproxy documentation.

Fix text search, part 2

---

ogcapi-custom/ogcapi-features-geojson-ld/src/main/java/de/ii/ogcapi/features/geojson/ld/app/EndpointJsonLdContext.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/QueryParameterF.java
ogcapi-stable/ogcapi-features-cityjson/src/main/java/de/ii/ogcapi/features/cityjson/app/FeaturesFormatCityJsonSeq.java

Closes #1198
This PR also fixes two similar cases in other building blocks.

fix handling of parameter f on collections

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/LayerControl/LegendSymbol/Line.js

fix line icons

---

ogcapi-custom/ogcapi-features-custom-extensions/src/main/java/de/ii/ogcapi/features/custom/extensions/app/QueryParameterIntersects.java

intersects parameter: quote property name to avoid keyword clashes

---

ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/domain/AbstractPathParameterCollectionId.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiExtensionHealth.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/Endpoint.java

Change map to concurrent to support async startup. Also adds debug messages.

fix startup errors

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/OpenLayers/proj.js
ogcapi-stable/ogcapi-tilematrixsets/src/main/java/de/ii/ogcapi/tilematrixsets/app/TileMatrixSetsBuildingBlock.java
ogcapi-stable/ogcapi-tilematrixsets/src/main/java/de/ii/ogcapi/tilematrixsets/domain/TileMatrixSetsConfiguration.java

Closes #1216.
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/274.
This also fixes bugs in the documentation and adds support for EPSG:25833 in OpenLayers.

add AdV TileMatrixSet for ETRS89/UTM33N

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/infra/rest/ApiRequestDispatcher.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/infra/rest/ExceptionMapper.java

Replace "TODO: generic message" error message on status 503.

update message on status 503

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/OpenLayers/DynamicSource/index.jsx
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/OpenLayers/index.jsx

support raster tiles in openlayers

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/QueriesHandlerStylesImpl.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleLegendFormatPng.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleRepositoryFiles.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StylesBuildingBlock.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/manager/QueryParameterDryRunStylesManager.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/PathParameterCollectionIdStyles.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/PathParameterStyleId.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/QueriesHandlerStyles.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StyleLegendFormatExtension.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StyleRepository.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StylesConfiguration.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StylesLinkGenerator.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/infra/EndpointStyleLegend.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/infra/EndpointStyleLegendCollection.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/infra/EndpointStyleMetadata.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiEndpointDefinition.java
ogcapi-stable/ogcapi-foundation/src/main/resources/i18n-de.properties
ogcapi-stable/ogcapi-foundation/src/main/resources/i18n-en.properties

-   [x] All checks are passing (locally, not on the build server; this seems to be a server issue)
Closes #1226.

Styles: add support for a legend

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleFormatMbStyle.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StylesBuildingBlock.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/MbStyleStylesheet.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/domain/StylesConfiguration.java

add bounds to the vector source of a MapLibre style

---

ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/EndpointFeature.java

check integer feature ids

---

ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/app/QueryablesBuildingBlock.java
ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/domain/QueryablesConfiguration.java

enable queryables by default

---

ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppConfigurationCfg.java
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/LdproxyCfgImpl.java
ogcapi-stable/ogcapi-foundation/src/testFixtures/groovy/de/ii/ogcapi/foundation/domain/AppConfigurationTest.java
xtraplatform.gradle

Closes #1267.
Depends on interactive-instruments/xtraplatform#166.

support substitutions from cfg.yml

---

ogcapi-custom/ogcapi-features-custom-extensions/src/main/java/de/ii/ogcapi/features/custom/extensions/app/QueryParameterIntersects.java
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterConformsTo.java
ogcapi-stable/ogcapi-features-geojson/src/main/java/de/ii/ogcapi/features/geojson/app/FeaturesFormatGeoJson.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TilesQueriesHandlerImpl.java
xtraplatform.gradle

Handle additional situations in case of a feature type with root concatenation.
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/286
Note: this does not merge into `master`, but into `root-concat`.

additional root concatenation changes

---

ogcapi-custom/ogcapi-codelists/src/main/java/de/ii/ogcapi/codelists/app/CodelistFormatHtml.java
ogcapi-custom/ogcapi-codelists/src/main/java/de/ii/ogcapi/codelists/app/CodelistsFormatHtml.java
ogcapi-custom/ogcapi-resources/src/main/java/de/ii/ogcapi/resources/app/ResourcesFormatHtml.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/StoredQueriesFormatHtml.java
ogcapi-draft/ogcapi-routes/src/main/java/de/ii/ogcapi/routes/app/html/RoutesFormatHtml.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StyleMetadataFormatHtml.java
ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/StylesFormatHtml.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/html/CollectionFormatHtml.java
ogcapi-stable/ogcapi-collections/src/main/java/de/ii/ogcapi/collections/app/html/CollectionsFormatHtml.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/app/html/ConformanceDeclarationFormatHtml.java
ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/app/html/LandingPageFormatHtml.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/CollectionPropertiesView.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeaturesFormatHtml.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiCatalogEntry.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiCatalogProvider.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/FoundationConfiguration.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/app/ServiceOverviewView.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/FormatHtml.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/HtmlConfiguration.java
ogcapi-stable/ogcapi-oas30/src/main/java/de/ii/ogcapi/oas30/app/OpenApiHtml.java
ogcapi-stable/ogcapi-tilematrixsets/src/main/java/de/ii/ogcapi/tilematrixsets/app/TileMatrixSetFormatHtml.java
ogcapi-stable/ogcapi-tilematrixsets/src/main/java/de/ii/ogcapi/tilematrixsets/app/TileMatrixSetsFormatHtml.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/html/TileSetsFormatHtml.java

Joint catalog

---

ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/app/QueryablesBuildingBlock.java

Closes #1288
Depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/291

 add checks on queryable properties

---

ogcapi-custom/ogcapi-codelists/src/main/java/de/ii/ogcapi/codelists/app/CodelistsFormatHtml.java
ogcapi-custom/ogcapi-codelists/src/main/java/de/ii/ogcapi/codelists/app/QueriesHandlerCodelistsImpl.java
ogcapi-custom/ogcapi-codelists/src/main/java/de/ii/ogcapi/codelists/domain/CodelistEntry.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/app/HtmlBuildingBlock.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/HtmlConfiguration.java

add suppressUnusedCodelistsInOverview

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/FilterEditor/Editor/Fields/index.jsx
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/FilterEditor/util.js

Issue 1262

---

ogcapi-stable/ogcapi-collections-queryables/src/main/java/de/ii/ogcapi/collections/queryables/app/QueryParameterTemplateQueryable.java

Map query parameters with DATE or DATETIME values to CQL2.
Closes #1308

support temporal queryables as parameters

---

ogcapi-draft/ogcapi-styles/src/main/java/de/ii/ogcapi/styles/app/MbStyleStylesheetGenerator.java

Fixes colors in the MapLibre style generator used by the editor.

fix auto style colors

---

ogcapi-custom/ogcapi-features-resulttype/src/main/java/de/ii/ogcapi/features/resulttype/app/QueryParameterResultTypeFeatures.java

fix building block of result-type parameter

---

ogcapi-custom/ogcapi-codelists/build.gradle
ogcapi-custom/ogcapi-features-resulttype/build.gradle

Upgrade maintenance level of building blocks `ogcapi-codelist` and `ogcapi-features-resulttype` to `low` (from `none`).
Closes #1325

Upgrade maintenance levels

---

ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/app/Format3DTilesTilesetHtml.java
ogcapi-draft/ogcapi-tiles3d/src/main/java/de/ii/ogcapi/tiles3d/app/TilesetView.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/app/FeaturesFormatHtml.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/domain/FeaturesView.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/app/StyleReaderImpl.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/HtmlConfiguration.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/StyleReader.java
ogcapi-stable/ogcapi-html/src/main/javascript/src/components/Cesium/index.jsx
ogcapi-stable/ogcapi-html/src/main/resources/de/ii/ogcapi/html/templates/data-cesium.mustache
ogcapi-stable/ogcapi-html/src/main/resources/de/ii/ogcapi/html/templates/mapClient.mustache
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/html/TileSetsFormatHtml.java

remove styles http access from backend

---

gradle/layers.versions.toml
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/EntityFactories.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreBuildingBlock.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/WithChangeListeners.java
ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/CollectionExtent.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/TileSeedingBackgroundTask.java

Closes #633.
Depends on interactive-instruments/xtraplatform#210
Depends on interactive-instruments/xtraplatform-spatial#326

Dataset change detection

---

gradle/layers.versions.toml
ogcapi-draft/ogcapi-features-jsonfg/src/main/java/de/ii/ogcapi/features/jsonfg/app/JsonFgWriterCrs.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchBuildingBlock.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchQueriesHandlerImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/QueryExpression.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/html/TileSetsView.java

Closes #1348.
Depends on https://github.com/ldproxy/xtraplatform-spatial/pull/328.

Improve support for ad-hoc compound CRS

---

ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointAdHocQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/EndpointStoredQuery.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/app/SearchQueriesHandlerImpl.java
ogcapi-draft/ogcapi-features-search/src/main/java/de/ii/ogcapi/features/search/domain/SearchQueriesHandler.java
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/app/FeaturesCoreQueriesHandlerImpl.java
ogcapi-stable/ogcapi-features-html/src/main/java/de/ii/ogcapi/features/html/domain/FeaturesView.java

remove outdated code on profiles, hide filter editor for multi-collection queries

---

ogcapi-draft/ogcapi-projections/src/main/java/de/ii/ogcapi/projections/app/QueryParameterExcludeProperties.java

Thanks for the analysis, @azahnen.
Closes #1371

Tile generation: only set or exclude properties, if explicitly requested

---

docs.gradle
gradle/layers.versions.toml
version.gradle

update tools docs

---

ogcapi-stable/ogcapi-html/src/main/javascript/src/components/MapLibre/Configuration/popup.js

change "MultiPoints" to "MultiPoint"

---

ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiCatalogProvider.java

fix tag filtering for additional entries

---

ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/app/StyleReaderImpl.java
ogcapi-stable/ogcapi-html/src/main/java/de/ii/ogcapi/html/domain/StyleReader.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetDataset.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetsCollection.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/AbstractEndpointTileSetsDataset.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/api/EndpointTileMixin.java
ogcapi-stable/ogcapi-tiles/src/main/java/de/ii/ogcapi/tiles/app/PathParameterStyleId.java

validate path parameter for style ids

---

composite/settings.gradle
gradle/layers.versions.toml
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppConfigurationCfg.java
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/AppContextCfg.java
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/LdproxyCfgImpl.java
ogcapi-custom/settings.gradle
ogcapi-draft/settings.gradle
ogcapi-stable/settings.gradle
settings.gradle

Closes #1389.
Depends on interactive-instruments/xtraplatform#225.
Depends on interactive-instruments/xtraplatform-spatial#341.

configurable yaml file size limit

---

gradle/layers.versions.toml
ldproxy-cfg/src/main/java/de/ii/ldproxy/cfg/OgcApiExtensionRegistry.java
ogcapi-draft/ogcapi-crud/src/main/java/de/ii/ogcapi/crud/app/CrudBuildingBlock.java

Closes #1408.
Depends on interactive-instruments/xtraplatform-spatial#357

Crud advanced

---

ogcapi-draft/ogcapi-collections-schema/build.gradle
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/app/QueriesHandlerSchemaFeatures.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/app/SchemaFormatHtmlSchema.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/app/SchemaFormatJsonSchema.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/app/SchemaView.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/domain/QueriesHandlerSchema.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/domain/SchemaFormatExtension.java
ogcapi-draft/ogcapi-collections-schema/src/main/java/de/ii/ogcapi/collections/schema/infra/EndpointSchema.java
ogcapi-draft/ogcapi-collections-schema/src/main/resources/de/ii/ogcapi/collections/schema/templates/schema.mustache
ogcapi-stable/ogcapi-features-core/build.gradle
ogcapi-stable/ogcapi-features-core/src/main/java/de/ii/ogcapi/features/core/domain/CollectionProperty.java

Ldp 57 html ansicht fur json schema
